// Code generated by protoc-gen-go.
// source: protobufs/collection.proto
// DO NOT EDIT!

/*
Package collection is a generated protocol buffer package.

It is generated from these files:
	protobufs/collection.proto

It has these top-level messages:
	Collection
*/
package collection

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Collection struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Capped           *bool   `protobuf:"varint,2,req,name=Capped" json:"Capped,omitempty"`
	MaxByteSize      *int64  `protobuf:"varint,3,opt,name=MaxByteSize" json:"MaxByteSize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Collection) Reset()                    { *m = Collection{} }
func (m *Collection) String() string            { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()               {}
func (*Collection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Collection) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Collection) GetCapped() bool {
	if m != nil && m.Capped != nil {
		return *m.Capped
	}
	return false
}

func (m *Collection) GetMaxByteSize() int64 {
	if m != nil && m.MaxByteSize != nil {
		return *m.MaxByteSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Collection)(nil), "Collection")
}

func init() { proto.RegisterFile("protobufs/collection.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0x2b, 0xd6, 0x4f, 0xce, 0xcf, 0xc9, 0x49, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf,
	0xd3, 0x03, 0x0b, 0x2a, 0xd9, 0x73, 0x71, 0x39, 0xc3, 0xc5, 0x84, 0x78, 0xb8, 0x58, 0xfc, 0x12,
	0x73, 0x53, 0x25, 0x18, 0x15, 0x98, 0x34, 0x38, 0x85, 0xf8, 0xb8, 0xd8, 0x9c, 0x13, 0x0b, 0x0a,
	0x52, 0x53, 0x24, 0x98, 0x80, 0x7c, 0x0e, 0x21, 0x61, 0x2e, 0x6e, 0xdf, 0xc4, 0x0a, 0xa7, 0xca,
	0x92, 0xd4, 0xe0, 0xcc, 0xaa, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x66, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf4, 0x31, 0x35, 0x22, 0x5d, 0x00, 0x00, 0x00,
}
